[package]
name = "croaring"
version = "0.5.1"
authors = ["Saulius Grigaliunas <saulius@ninja.lt>"]
license = "Apache-2.0"
description = "Rust wrapper for CRoaring"
repository = "https://github.com/saulius/croaring-rs.git"
readme = "../README.md"
keywords = ["RoaringBitmap", "croaring", "bitmap"]
documentation = "https://docs.rs/croaring"

[dev-dependencies]
proptest = "1"
roaring = "0.7"

[dependencies]
libc = "0.2"
croaring-sys = { path = "../croaring-sys", version = "0.5.1" }
byteorder = "1"
