[package]
name = "croaring"
version = "0.9.0"
edition = "2021"
authors = ["croaring-rs developers"]
license = "Apache-2.0"
description = "Rust wrapper for CRoaring"
repository = "https://github.com/RoaringBitmap/croaring-rs.git"
readme = "../README.md"
keywords = ["RoaringBitmap", "croaring", "bitmap"]
documentation = "https://docs.rs/croaring"

[features]
default = []
buildtime_bindgen = ["ffi/buildtime_bindgen"]

[dev-dependencies]
proptest = "1"
roaring = "0.10"

[dependencies]
ffi = { package = "croaring-sys", path = "../croaring-sys", version = "0.9.0" }
byteorder = "1"
