[package]
name = "croaring"
version = "0.8.0"
edition = "2021"
authors = ["Saulius Grigaliunas <saulius@ninja.lt>"]
license = "Apache-2.0"
description = "Rust wrapper for CRoaring"
repository = "https://github.com/saulius/croaring-rs.git"
readme = "../README.md"
keywords = ["RoaringBitmap", "croaring", "bitmap"]
documentation = "https://docs.rs/croaring"

[features]
default = []
buildtime_bindgen = ["ffi/buildtime_bindgen"]

[dev-dependencies]
proptest = "1"
roaring = "0.10"

[dependencies]
ffi = { package = "croaring-sys", path = "../croaring-sys", version = "0.8.0" }
byteorder = "1"
